[package]
name = "gol_rs"
version = "0.1.0"
authors = ["cyberparty <jc@cyberparty.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
